// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/29 11:41:00
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/lizhenhu/Desktop/zhihe-0520-3/daily-schedule-planner/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0520-3/daily-schedule-planner/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0520-3/daily-schedule-planner/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0520-3/daily-schedule-planner/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0520-3/daily-schedule-planner/plugins/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0520-3/daily-schedule-planner/composables/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0520-3/daily-schedule-planner/utils/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0520-3/daily-schedule-planner/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0520-3/daily-schedule-planner/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0520-3/daily-schedule-planner/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0520-3/daily-schedule-planner/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;